import * as React from "react";
import Head from "next/head";

import BasicTabs from "../components/TabPanel";
import Layout from "../components/Layout";

import Box from "@mui/material/Box";
import LinearProgress from "@mui/material/LinearProgress";

export default function Home() {
  const [progress, setProgress] = React.useState(0);

  React.useEffect(() => {
    const timer = setInterval(() => {
      setProgress((oldProgress) => {
        if (oldProgress === 100) {
          return 0;
        }
        const diff = Math.random() * 10;
        return Math.min(oldProgress + diff, 100);
      });
    }, 500);

    return () => {
      clearInterval(timer);
    };
  }, []);

  return (
    <React.Fragment>
      <Head>
        <title>Status Order</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <BasicTabs />
      </Layout>
    </React.Fragment>
  );
}
